[package]
name = "doco"
version = "0.1.0"
authors = ["Do Nhat Minh <mrordinaire@gmail.com>", "Renato Costa", "Shayan Mohammed"]
keywords = ["documentation"]
categories = ["documentation"]

[dependencies]
